In [1]:
from scipy.stats import poisson
import numpy as np

In [2]:
poisson.pmf(0,1.23)

0.2922925776808594

In [3]:
def poisson_pmf(k, lam):
    return (lam**k*np.exp(-lam))/np.math.factorial(k)
poisson_pmf(0,1.23)

0.2922925776808594

In [4]:
n_goals = [0,1,2,3,4,5]

In [5]:
def poisson_pmf_goals_home(n_goals, lam):
    probs = []
    for k in n_goals:
        probs.append((lam**k*np.exp(-lam))/np.math.factorial(k))
    return (np.array([probs,]*6)).T
home = poisson_pmf_goals_home(n_goals,1.23)
home

array([[0.29229258, 0.29229258, 0.29229258, 0.29229258, 0.29229258,
        0.29229258],
       [0.35951987, 0.35951987, 0.35951987, 0.35951987, 0.35951987,
        0.35951987],
       [0.22110472, 0.22110472, 0.22110472, 0.22110472, 0.22110472,
        0.22110472],
       [0.09065294, 0.09065294, 0.09065294, 0.09065294, 0.09065294,
        0.09065294],
       [0.02787578, 0.02787578, 0.02787578, 0.02787578, 0.02787578,
        0.02787578],
       [0.00685744, 0.00685744, 0.00685744, 0.00685744, 0.00685744,
        0.00685744]])

In [6]:
def poisson_pmf_goals_away(n_goals, lam):
    probs = []
    for k in n_goals:
        probs.append((lam**k*np.exp(-lam))/np.math.factorial(k))
    return np.array([probs,]*6)
away = poisson_pmf_goals_away(n_goals,0.997)
away

array([[0.36898474, 0.36787778, 0.18338707, 0.06094564, 0.0151907 ,
        0.00302903],
       [0.36898474, 0.36787778, 0.18338707, 0.06094564, 0.0151907 ,
        0.00302903],
       [0.36898474, 0.36787778, 0.18338707, 0.06094564, 0.0151907 ,
        0.00302903],
       [0.36898474, 0.36787778, 0.18338707, 0.06094564, 0.0151907 ,
        0.00302903],
       [0.36898474, 0.36787778, 0.18338707, 0.06094564, 0.0151907 ,
        0.00302903],
       [0.36898474, 0.36787778, 0.18338707, 0.06094564, 0.0151907 ,
        0.00302903]])

In [7]:
prob = home*away
prob

array([[1.07851500e-01, 1.07527945e-01, 5.36026807e-02, 1.78139576e-02,
        4.44012892e-03, 8.85361707e-04],
       [1.32657345e-01, 1.32259373e-01, 6.59312973e-02, 2.19111678e-02,
        5.46135857e-03, 1.08899490e-03],
       [8.15842670e-02, 8.13395142e-02, 4.05477478e-02, 1.34753682e-02,
        3.35873552e-03, 6.69731863e-04],
       [3.34495495e-02, 3.33492008e-02, 1.66245766e-02, 5.52490096e-03,
        1.37708156e-03, 2.74590064e-04],
       [1.02857365e-02, 1.02548793e-02, 5.11205731e-03, 1.69890705e-03,
        4.23452581e-04, 8.44364447e-05],
       [2.53029117e-03, 2.52270030e-03, 1.25756610e-03, 4.17931133e-04,
        1.04169335e-04, 2.07713654e-05]])

In [8]:
np.set_printoptions(suppress=True)
prob*100

array([[10.78514998, 10.75279453,  5.36026807,  1.78139576,  0.44401289,
         0.08853617],
       [13.26573447, 13.22593727,  6.59312973,  2.19111678,  0.54613586,
         0.10889949],
       [ 8.1584267 ,  8.13395142,  4.05477478,  1.34753682,  0.33587355,
         0.06697319],
       [ 3.34495495,  3.33492008,  1.66245766,  0.5524901 ,  0.13770816,
         0.02745901],
       [ 1.02857365,  1.02548793,  0.51120573,  0.1698907 ,  0.04234526,
         0.00844364],
       [ 0.25302912,  0.25227003,  0.12575661,  0.04179311,  0.01041693,
         0.00207714]])

In [9]:
import pandas as pd
df = pd.DataFrame(prob, columns = ['0','1','2','3','4','5'], index = ['0','1','2','3','4','5'])
df

0         1         2         3         4         5
0  0.107851  0.107528  0.053603  0.017814  0.004440  0.000885
1  0.132657  0.132259  0.065931  0.021911  0.005461  0.001089
2  0.081584  0.081340  0.040548  0.013475  0.003359  0.000670
3  0.033450  0.033349  0.016625  0.005525  0.001377  0.000275
4  0.010286  0.010255  0.005112  0.001699  0.000423  0.000084
5  0.002530  0.002523  0.001258  0.000418  0.000104  0.000021

In [10]:
df.loc['0', '0']

0.10785149978837902

In [11]:
from itertools import combinations_with_replacement
from collections import OrderedDict
combs = list(OrderedDict.fromkeys(list(combinations_with_replacement(['0','1','2','3','4','5','4','3','2','1','0'], 2))))

In [12]:
for i in range (0, len(combs)):
    
    if (combs[i][0]) > (combs[i][1]):
        print (combs[i])

('1', '0')
('2', '1')
('2', '0')
('3', '2')
('3', '1')
('3', '0')
('4', '3')
('4', '2')
('4', '1')
('4', '0')
('5', '4')
('5', '3')
('5', '2')
('5', '1')
('5', '0')


In [13]:
for i in range (0, len(combs)):
    x = combs[i][0]
    y = combs[i][1]
    if x >= y:
        print(combs[i])

('0', '0')
('1', '1')
('1', '0')
('2', '2')
('2', '1')
('2', '0')
('3', '3')
('3', '2')
('3', '1')
('3', '0')
('4', '4')
('4', '3')
('4', '2')
('4', '1')
('4', '0')
('5', '5')
('5', '4')
('5', '3')
('5', '2')
('5', '1')
('5', '0')


In [14]:
z = df.loc[combs[0]]
z

0.10785149978837902

In [15]:
res = sum(df.loc[combs[i]] for i in range (0, len(combs)) if combs[i][0] == combs[i][1])
res

0.28662774523687945